[tool.black]
line-length = 130
target-version = ['py310']

[tool.pytest.ini_options]
testpaths = ["app/sa/core/tests"]
addopts = ["-vvv", "--tb=short", "--cov=app/sa/core", "--cov-report=term-missing"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::FutureWarning",
]

[tool.isort]
profile = "black"
line_length = 130

[tool.ruff]
line-length = 130
target-version = 'py310'

[tool.flake8]
ignore = ["E501", "W291"]

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "basic"
include = ["app/sa"]
exclude = ["**/tests/**", "**/migrations/**"]

reportMissingImports = false
reportMissingTypeStubs = false
reportAttributeAccessIssue = false
reportGeneralTypeIssues = false
reportCallIssue = false

reportAssignmentType = false
reportReturnType = true
reportUndefinedVariable = true
reportArgumentType = false

[tool.coverage.run]
source = ["app/sa/core"]
omit = ["*/tests/*", "*/migrations/*"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
]
